### ISSUE TITLE
Run notebook tests only if the commit message contains a special string

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#184]
Compared to AI-Lab unit- and integration tests currently notebook tests take very long.

Similar to CodeBuild this ticket requests to only execute the long-running notebook tests if the commit message contains a special string.

**Comment by ckunki** [comment]
See https://stackoverflow.com/a/75004411 
```yaml
jobs:
  Build-my-project-for-Linux:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'please build')
    steps:
```
